# 프로그래머스_완전탐색_카펫

Leo는 카펫을 사러 갔다가 아래 그림과 같이 중앙에는 노란색으로 칠해져 있고 테두리 1줄은 갈색으로 칠해져 있는 격자 모양 카펫을 봤습니다.  
Leo는 집으로 돌아가서 아까 본 카펫의 노란색과 갈색으로 색칠된 격자의 개수는 기억했지만, 전체 카펫의 크기는 기억하지 못했습니다.  
Leo가 본 카펫에서 갈색 격자의 수 brown, 노란색 결자의 수 yellow가 매개변수로 주어질 때 카펫의 가로, 세로 크기를 순서대로 배열에 담아 return 하도록 solution 함수를 작성해주세요.  
제한사항  
- 갈색 격자 수 brown은 8 이상 5,000 이하인 자연수입니다.
- 노란색 격자의 수 yellow는 1 이상 2,000,000 이하인 자연수입니다.
- 카펫의 가로 길이는 세로 길이와 같거나, 세로 길이보다 깁니다.

In [1]:
import numpy as np

In [70]:
brown = 10
yellow = 2

In [4]:
brown = 8
yellow = 1

In [51]:
brown = 24
yellow = 24

In [3]:
def solution(brown, yellow):
    answer = []
    return answer

In [29]:
ylow = np.zeros((1,1))
ylow

array([[0.]])

In [32]:
brown_pad = np.pad(ylow, ((1,1),(1,1)), 'constant', constant_values = 1)
brown_pad

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [36]:
np.count_nonzero(brown_pad == 1)

8

In [39]:
np.count_nonzero(brown_pad == 0)

1

In [45]:
area = brown + yellow
circumference = brown + 4
circumference

14

In [48]:
a = (brown + 4 + (1/2)**((brown**2) - 8*yellow + 16)) / 4
b = (brown + yellow) / a
print(a)
print(b)

3.5
3.4285714285714284


In [47]:
a

3.5

In [41]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [67]:
area = brown + yellow
for width in range(1, area):
    if area % width == 0:
        height = area / width
        if (2*width + 2*height == brown + 4) & (width >= height):
            answer = [width, height]
        
    

In [68]:
answer

[8, 6.0]

In [ ]:
area = brown + yellow
for width in range(1, area):
    if area % width == 0:
        height = area / width
        if (2*width + 2*height == brown + 4) & (width >= height):
            answer = [width, height]
        
    

In [71]:
def solution(brown, yellow):
    area = brown + yellow
    for width in range(1, area):
        if area % width == 0:
            height = area / width
            if (2*width + 2*height == brown + 4) & (width >= height):
                answer = [width, height]
    return answer

In [72]:
solution(brown, yellow)

[4, 3.0]